// <auto-generated />
namespace OA.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addsys_rolecolumnparentId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsys_rolecolumnparentId));
        
        string IMigrationMetadata.Id
        {
            get { return "201709291328046_add sys_role column parentId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
