// <auto-generated />
namespace OA.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Role_Set_Required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Role_Set_Required));
        
        string IMigrationMetadata.Id
        {
            get { return "201709300324050_Role_Set_Required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
